### ISSUE TITLE
Error on Attempting to Add Installers

### ISSUE THREAD

**Issue by AC1DFOX** [kingjacob280/BuildTools#12]
When attempting to add installers, the program generates an error message shown below: 
<img width="601" alt="Add Installers" src="https://user-images.githubusercontent.com/75289053/100690675-aa24c680-334c-11eb-9905-cc337e37de14.PNG">

**Comment by JacobMS2020** [comment]
Hi

Thank you for your bug report.

I will recreate the error and update the program as soon as a solution is found.

Kind regards,
Jacob

**Comment by JacobMS2020** [comment]
Hi @AC1DFOX 

This error is because you have not extracted the 'Build Tools' folder from the .zip file you download (or have deleted it or did not downloaded it in the first place). 
Please download the 'Build Tools' folder again and extract it before running the program. 

There will be better error prevention code in the next update to explain this error if it happens again for you or other users.

**Comment by AC1DFOX** [comment]
I actually downloaded the direct installer here:  https://github.com/kingjacob280/BuildTools/blob/main/Build%20Tools%205.1.0.2.exe

There was no zipped archive to extract, just a straight installer.

**Comment by kingjacob280** [comment]
Please try using this link: [](https://github.com/kingjacob280/BuildTools/releases/tag/5.1.0.2 )

**Comment by JacobMS2020** [comment]
Please try using this link: https://github.com/kingjacob280/BuildTools/releases/tag/5.1.0.2
